# Generated by Django 5.0.1 on 2024-01-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='visualizer.project'),
        ),
    ]
