services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: visualizer
    volumes:
      - .:/visualizer
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: iebs_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@123
