services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "gunicorn -b 0.0.0.0:8000 IebsAnalytics.wsgi:application"
    container_name: visualizer
    volumes:
      - .:/visualizer
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - .:/visualizer

    ports:
      - "8088:8088"
    depends_on:
      - web